### ISSUE TITLE
Optim stat()

### ISSUE THREAD

**Issue by kcgthb** [stanford-rc/fuse-migratefs#14]
With fd.

**Comment by thiell** [comment]
c7c4dbd makes use of the fd provided by FUSE in `getattr()` if the file is open, so in this case, at each getattr we avoid:
* a lookup which takes a lock on migratefs' inode cache and does a check for the file in all layers
* a fstatat using the full path (we still need to do a `fstat()` by fd only)

Reading a file should now be lockless, so I expect this change to provide a performance improvement on read in multi-threaded mode, especially under mixed workload. This is worth a 0.3.2.
