### ISSUE TITLE
Is there a reason that you forked fuse-overlayfs?

### ISSUE THREAD

**Issue by rhatdan** [stanford-rc/fuse-migratefs#19]
We would love to work with you on improving fuse-overlayfs.

@giuseppe FYI

**Comment by vbatts** [comment]
sounds like they have some grid filesystem unique to standford infrastructure?
seems like if there were hooks or triggers for events, then they could just write a utility to purge files from their Lustra when the upper file changes. As for detecting mutations in the lower directory, surely that can be generic

**Comment by kcgthb** [comment]
@rhatdan @vbatts Yes, there is! :grin: 

Sorry for the delay answering your question, but yes, there's a reason we forked it: we needed a starting point to build a new filesystem overlay four our own need, which is to transparently migrate active user data from one filesystem to another, in a distributed fashion, and with minimum downtime. This is in the context of a massively parallel HPC cluster, using a distributed Lustre filesystem: this filesystem needs to be retired and replaced by a newer one, and user data needs to be migrated with a minimum of disruption.

The basic idea is to present a stacked view of the new and old filesystems to the users, to redirect their writes to the upper layer, allow reads on all layers, and migrate the files that are modified from the lower to the upper layer. So active files gets transferred to the new filesystem, and the old ones stay on the lower one. 

We're in the process of writing some more detailed description about `migratefs`, to explain the rationale, and its inner workings, and it will also be presented at the Lustre User Group: https://conference.cacds.uh.edu/program/

**Comment by rhatdan** [comment]
Ok, well any problems that you find in your file system, that could affect fuse-overlay we would appreciate hearing about.

**Comment by kcgthb** [comment]
Definitely! @thiell reported some and opened a few PRs already:
https://github.com/containers/fuse-overlayfs/issues?utf8=%E2%9C%93&q=author%3Athiell+
