### ISSUE TITLE
Explore sendfile() for copyup operations

### ISSUE THREAD

**Issue by kcgthb** [stanford-rc/fuse-migratefs#4]
Maybe [`sendfile()`](http://man7.org/linux/man-pages/man2/sendfile.2.html) could be used instead of `read()`/`write()` to make copyup operations more efficient?

**Comment by giuseppe** [comment]
I've a PR here: https://github.com/containers/fuse-overlayfs/pull/62

**Comment by thiell** [comment]
Thanks @giuseppe this was super helpful. But I think I found an issue when sendfile returns -1, you then did `copied += n` which could be a problem. I changed that a bit.

**Comment by thiell** [comment]
@giuseppe Submitted as PR containers/fuse-overlayfs/pull/70 for review
