### ISSUE TITLE
Create a test suite

### ISSUE THREAD

**Issue by kcgthb** [stanford-rc/fuse-migratefs#5]
We'll need a test suite for functionality testing and non-regression tests.
The existing Travis file from forked fuse-overlayfs  is probably a good starting point.

Tests to implement would cover:
- [ ] `overlayfs`-type functionality, especially focused on the copyup operations
- [ ] [fstest](https://github.com/zfsonlinux/fstest) POSIX Filesystem Test Suite
- [ ] specific cases addressed in previous bugfixes (xattr testing...)

**Comment by thiell** [comment]
Done in f794d752f3518bcca396d3314a9d3812554cbec7 and following commits.
The full fstest suite is run with a few patches to accommodate minor behavior changes.
copyup operations are tested by a specific test script
stress-ng --class filesystem is also performed
