### ISSUE TITLE
Command line options: multi-threading

### ISSUE THREAD

**Issue by kcgthb** [stanford-rc/fuse-migratefs#7]
Provide command-line options to:
- [ ] enable/disable multi-threading 
- [x] specify the (maximum?) number of threads

Depends on #6

**Comment by thiell** [comment]
FUSE uses as many threads as needed to process I/Os (except for forget calls),
and keeps a pool of idle threads. The max idle threads can be set using the
following migratefs option:

-o max_idle_threads=32

Having sufficient idle threads avoids thread creation overhead under load.

The default max_idle_threads is 10.

**Comment by thiell** [comment]
Added `-o mt=0` to switch off libfuse multithreading in 54d13e7 (`mt=1` is the default)
